fixed check of required programs

diff --git a/tardis b/tardis
--- a/tardis
+++ b/tardis
@@ -16,6 +16,8 @@ SHINY="N"
 GROUPFILE=""
 PROF="local"
 LOGFILE="tardis-$(date -Iminutes).txt"
+NEEDED="Rscript nextflow"
+
 # Colors are fun...
 B='\033[1;34m'
 Y='\033[1;33m'
@@ -55,21 +57,12 @@ then
   module load R
 fi  
 
-# Check that required external programs are available
-for prog in Rscript nextflow;
-do
-  if ! command -v $prog &> /dev/null
-  then 
-    echo "Warning: $prog not found in path!"
-    exit 1
-  fi
-done
-
 # Parse command-line options
   while getopts ":g:p:b:r:n:a:d:m:o:xshv" opt; do
 	case ${opt} in
 	    s )
 		SHINY="Y"
+		NEEDED="Rscript"
 		;;
 	    g )
 		GROUPFILE=$OPTARG
@@ -129,6 +122,16 @@ done
     done
 
   shift $((OPTIND - 1))
+
+  # Check that required external programs are available
+  for prog in $NEEDED;
+  do
+    if ! command -v $prog &> /dev/null
+    then 
+      echo "Warning: $prog not found in path!"
+      exit 1
+    fi
+  done
 
   # If running Shiny, ignore all other options and exit when done
   if [ "$SHINY" == "Y" ];
